alter table public.news
    add column if not exists status text not null default 'draft',
    add column if not exists published_at timestamptz,
    add column if not exists author_id uuid references auth.users(id) on delete set null,
    add column if not exists cover_image_url text,
    add column if not exists image_metadata jsonb not null default '[]'::jsonb,
    add column if not exists likes_count bigint not null default 0,
    add column if not exists shares_count bigint not null default 0,
    add column if not exists comments_count bigint not null default 0;

alter table public.news drop constraint if exists news_status_check;
alter table public.news add constraint news_status_check check (status in ('draft', 'published', 'archived'));

-- Keep existing news available to clients that already consume the table.
update public.news
set status = 'published',
    published_at = coalesce(published_at, created_at, now())
where published_at is null;

create table if not exists public.news_likes (
    id bigint generated by default as identity primary key,
    news_id bigint not null references public.news(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (news_id, user_id)
);

create table if not exists public.news_comments (
    id bigint generated by default as identity primary key,
    news_id bigint not null references public.news(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    author_name text not null,
    body text not null check (char_length(body) between 1 and 4000),
    status text not null default 'visible' check (status in ('visible', 'hidden')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.news_shares (
    id bigint generated by default as identity primary key,
    news_id bigint not null references public.news(id) on delete cascade,
    user_id uuid references auth.users(id) on delete set null,
    platform text not null default 'native' check (platform in ('native', 'whatsapp', 'facebook', 'instagram', 'copy_link', 'other')),
    created_at timestamptz not null default now()
);

create index if not exists news_published_feed_idx on public.news (published_at desc, id desc) where status = 'published';
create index if not exists news_likes_news_id_idx on public.news_likes (news_id);
create index if not exists news_comments_feed_idx on public.news_comments (news_id, created_at desc) where status = 'visible';
create index if not exists news_shares_news_id_idx on public.news_shares (news_id);

alter table public.news enable row level security;
alter table public.news_likes enable row level security;
alter table public.news_comments enable row level security;
alter table public.news_shares enable row level security;

drop policy if exists "Published news is public; owner can read all" on public.news;
create policy "Published news is public; owner can read all"
on public.news for select to anon, authenticated
using (status = 'published' or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

drop policy if exists "News owner can create posts" on public.news;
create policy "News owner can create posts"
on public.news for insert to authenticated
with check (
    lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com'
    and (author_id is null or author_id = auth.uid())
);

drop policy if exists "News owner can update posts" on public.news;
create policy "News owner can update posts"
on public.news for update to authenticated
using (lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com')
with check (lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

drop policy if exists "News owner can delete posts" on public.news;
create policy "News owner can delete posts"
on public.news for delete to authenticated
using (lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

drop policy if exists "Likes are readable by everyone" on public.news_likes;
drop policy if exists "Users can read their own likes" on public.news_likes;
create policy "Users can read their own likes"
on public.news_likes for select to authenticated
using (user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');
drop policy if exists "Authenticated users can like news" on public.news_likes;
create policy "Authenticated users can like news"
on public.news_likes for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists "Users can remove their own likes" on public.news_likes;
create policy "Users can remove their own likes"
on public.news_likes for delete to authenticated
using (user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

drop policy if exists "Visible comments are public" on public.news_comments;
create policy "Visible comments are public"
on public.news_comments for select to anon, authenticated
using (status = 'visible' or user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');
drop policy if exists "Authenticated users can comment on published news" on public.news_comments;
create policy "Authenticated users can comment on published news"
on public.news_comments for insert to authenticated
with check (
    user_id = auth.uid()
    and exists (select 1 from public.news n where n.id = news_id and n.status = 'published')
);
drop policy if exists "Authors and owner can update comments" on public.news_comments;
create policy "Authors and owner can update comments"
on public.news_comments for update to authenticated
using (user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com')
with check (user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');
drop policy if exists "Authors and owner can delete comments" on public.news_comments;
create policy "Authors and owner can delete comments"
on public.news_comments for delete to authenticated
using (user_id = auth.uid() or lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

drop policy if exists "Shares can be recorded" on public.news_shares;
create policy "Shares can be recorded"
on public.news_shares for insert to anon, authenticated
with check (
    (user_id is null or user_id = auth.uid())
    and exists (select 1 from public.news n where n.id = news_id and n.status = 'published')
);
drop policy if exists "News owner can view share activity" on public.news_shares;
create policy "News owner can view share activity"
on public.news_shares for select to authenticated
using (lower(auth.jwt() ->> 'email') = 'eduardoibarra904@gmail.com');

create or replace function public.refresh_news_engagement_counts()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_table_name = 'news_likes' then
        if tg_op = 'INSERT' then
            update public.news set likes_count = likes_count + 1 where id = new.news_id;
            return new;
        elsif tg_op = 'DELETE' then
            update public.news set likes_count = greatest(likes_count - 1, 0) where id = old.news_id;
            return old;
        end if;
    elsif tg_table_name = 'news_shares' then
        if tg_op = 'INSERT' then
            update public.news set shares_count = shares_count + 1 where id = new.news_id;
            return new;
        end if;
    elsif tg_table_name = 'news_comments' then
        if tg_op = 'INSERT' then
            update public.news set comments_count = comments_count + 1 where id = new.news_id;
            return new;
        elsif tg_op = 'DELETE' then
            update public.news set comments_count = greatest(comments_count - 1, 0) where id = old.news_id;
            return old;
        end if;
    end if;
    return null;
end;
$$;

drop trigger if exists news_likes_count_trigger on public.news_likes;
create trigger news_likes_count_trigger after insert or delete on public.news_likes
for each row execute function public.refresh_news_engagement_counts();
drop trigger if exists news_shares_count_trigger on public.news_shares;
create trigger news_shares_count_trigger after insert on public.news_shares
for each row execute function public.refresh_news_engagement_counts();
drop trigger if exists news_comments_count_trigger on public.news_comments;
create trigger news_comments_count_trigger after insert or delete on public.news_comments
for each row execute function public.refresh_news_engagement_counts();

grant select on public.news, public.news_likes, public.news_comments to anon, authenticated;
grant insert, update, delete on public.news to authenticated;
grant insert, delete on public.news_likes to authenticated;
grant insert, update, delete on public.news_comments to authenticated;
grant insert on public.news_shares to anon, authenticated;
grant select on public.news_shares to authenticated;
grant usage, select on sequence public.news_likes_id_seq, public.news_comments_id_seq, public.news_shares_id_seq to anon, authenticated;
